---
- name: Copy {{ config_file.name }} file into the node
  raw: scp -i {{ ansible_ssh_private_key_file }} -P {{ ansible_port }} {{ config_file.src_path }}/{{ config_file.name }} {{ ansible_user }}@{{ ansible_host }}:~/
  delegate_to: localhost
  changed_when: false
  no_log: true

- name: Check for changes between new {{ config_file.name }} and current {{ config_file.dst }}
  raw: diff {{ config_file.name }} {{ config_file.dst }}
  ignore_errors: yes
  changed_when: false
  no_log: true
  register: config_comparison

- name: Remove {{ config_file.name }} file (there are no differences)
  raw: rm -rf {{ config_file.name }}
  when: not config_comparison.failed
  changed_when: false

- name: Copy {{ config_file.name }} file and reboot node
  raw: cp {{ config_file.name }} {{ config_file.dst }} && rm {{ config_file.name }}
  changed_when: true
  become: yes
  notify:
    - Reboot Node
  when: config_comparison.failed
