---
# Full configuration reference: https://github.com/rancher/k3os#configuration
hostname: asgard
k3OS:
  labels:
    region: home
    k3os.io/upgrade: enabled
  ntp_servers:
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
  dns_nameservers:
    - 1.1.1.1
    - 1.0.0.1
  k3s_args:
    - server
    - "--cluster-init"
    - "--disable=traefik,servicelb"
