# syntax=docker/dockerfile:1.3-labs
FROM alpine:3.12

ARG USER="ansible-client"
ARG ANSIBLE_VERSION="4.4.0"
# Fix pip build
ARG CRYPTOGRAPHY_DONT_BUILD_RUST=1

# hadolint ignore=DL3018
RUN <<EOF
# Add non-root user
addgroup -S $USER && adduser -S -G $USER $USER
# Install python3 and dependencies
apk --no-cache add python3 py3-pip openssl ca-certificates sshpass openssh-client rsync gettext git
apk --no-cache add --virtual build-dependencies python3-dev libffi-dev openssl-dev build-base
# Install ansible
pip3 install --no-cache-dir --upgrade pip ansible~=${ANSIBLE_VERSION} ansible-lint
apk del build-dependencies
rm -rf /var/cache/apk/*
EOF

# Set non-root user
WORKDIR /home/$USER
USER $USER
